"""
PES - Pandemic Experiment Scenario

Utility functions used throughout experiment (RL-Agent mode)
 • calculate_normalised_final_severity_performance_metric
 • chain_ops
 • create_subject_id
 • generate_feedback
 • get_confidence_weighted_mean
 • get_confidence_weighted_median
 • get_sequence_severity_from_allocations
 • get_updated_severity
 • next_seq_length
 • print_experiment_results_summary
 • plot_experiment_results
 • random_severity_generator
 • rgb_from_severity
 • sampler
 • toggle_experiment_mode
 • exit_experiment_gracefully
"""


# ----------------
# external imports
# ----------------

import os
import glob
import random
import numpy
import matplotlib.backends.backend_agg as agg
import matplotlib.pyplot as plt

from statsmodels.stats.weightstats import DescrStatsW as WeightedStats


# ----------------
# internal imports
# ----------------

from .. import ALLOCATION_TYPE
from .. import ANSI
from .. import BLOCK_MODE_INDICES
from .. import INIT_NO_OF_CITIES
from .. import INPUTS_PATH
from .. import MAX_ALLOCATABLE_RESOURCES
from .. import MIN_ALLOCATABLE_RESOURCES
from .. import NUM_BLOCKS
from .. import NUM_SEQUENCES
from .. import OUTPUTS_PATH, OUTPUT_FILE_PREFIX
from .. import PLAYER_TYPE
from .. import RESPONSE_MULTIPLIER
from .. import SEVERITY_MULTIPLIER
from .. import SEQ_LENGTHS_FILE


# -----------------------
# module-global variables
# -----------------------

AllocationType = ALLOCATION_TYPE


#############################
### General utility functions
#############################

def calculate_normalised_final_severity_performance_metric( SeveritiesFromSequence, InitialSequenceSeverities ):

    FinalSequenceSeverity     = numpy.sum( SeveritiesFromSequence )
    BestCaseAllocations       = numpy.full_like( SeveritiesFromSequence, MAX_ALLOCATABLE_RESOURCES )
    WorstCaseAllocations      = numpy.full_like( SeveritiesFromSequence, MIN_ALLOCATABLE_RESOURCES )
    BestCaseSequenceSeverity  = get_sequence_severity_from_allocations( BestCaseAllocations , InitialSequenceSeverities )
    WorstCaseSequenceSeverity = get_sequence_severity_from_allocations( WorstCaseAllocations, InitialSequenceSeverities )
    Performance               = (WorstCaseSequenceSeverity - FinalSequenceSeverity) / (WorstCaseSequenceSeverity - BestCaseSequenceSeverity )

    return Performance, WorstCaseSequenceSeverity, BestCaseSequenceSeverity




def get_sequence_severity_from_allocations( Allocations, InitialSeverities ):
    return numpy.sum( get_array_of_sequence_severities_from_allocations( Allocations, InitialSeverities ) )




def get_array_of_sequence_severities_from_allocations( Allocations, InitialSeverities ):
    '''
    This example shows how the city damage is performed in the current version of the experiment

    severities 3,4,8
    allocations 5,6,4

    3       |
    2.6 (5) |   4    |
    2.12(5) | 3.6 (6)|   8
    1.54(5) | 3.12(6)| 8.8 (4)

    Each individual severity is clipped to max(0, value)
    '''

    NumTrialsInSequence = len( InitialSeverities )
    severities          = []
    resources           = []

    for Trial in range( NumTrialsInSequence ):

        severities . append( InitialSeverities [ Trial ] )
        resources  . append( Allocations       [ Trial ] )

        severities = get_updated_severity( len( severities ), resources, severities )


    return severities.copy()




def create_subject_id() -> None :
    """
    Detects last subject number on the server, and increments by one, for use in tagging files generated by this
    experiment.
    """

    Prefix = f"{OUTPUT_FILE_PREFIX}log_"
    Suffix = ".txt"

    PrefixLength = len( Prefix )
    SuffixLength = len( Suffix )

    Subject_infoFiles = chain_ops( os.path.join( OUTPUTS_PATH, f'{Prefix}*{Suffix}' )
                                  , glob.glob
                                  , sorted
                                )
    Subject_infoFiles = [ os.path.basename( Str ) for Str in Subject_infoFiles ]

    SubjectIds = [ Str[ PrefixLength : -SuffixLength ] for Str in Subject_infoFiles ]   # keep only identifier part of files
    SubjectIds = [ Str[ : -5 ] if Str.endswith( '_TEST' ) else Str for Str in SubjectIds ]   # strip _TEST suffix if present
    SubjectIds = [ Str for Str in SubjectIds if Str.isdigit() ]                         # discard non numeric ids

    if SubjectIds == []: SubjectId = '001'
    else:
        SubjectId  = chain_ops( [ int(Str) for Str in SubjectIds ]   # reframe as numbers
                                , max                                # get the maximum
                                , lambda _ : _ + 1                   # increment by 1
                                , lambda _ : f"{_:0>3}"              # convert back to string, zero-padded up to three digits
                              )

    return SubjectId




def exit_experiment_gracefully( Message, Filehandles, MovementData, LogUtils, PygameMediator ):
    """
    Exit experiment gracefully, closing pygame, open files, and logging things appropriately.

    Note: We require the LogUtils and PygameMediator modules here as arguments, in order to avoid the cyclic dependency
    problem that would arise if we were to import them at the module level instead.
    """

  # Output helpful message - use these values in config to 'resume' a subsequent experiment
    LogUtils.tee()
    LogUtils.tee( Message )

  # Tidy up remaining resources
    numpy.save( *MovementData )
    PygameMediator.gracefully_quit_pygame()
    for Filehandle in Filehandles:
        if Filehandle is not None:   Filehandle.close()
    LogUtils.close_consolelog_filehandle()




def chain_ops( Accumulant, *Functions_list ):
    """
    Chain Operations: Pipe an input into a series of functions, each of which receives as input the output of the
    previous one (i.e. like bash '|' pipes, or R's magrittr %>% operator, etc.
    """
    for f in Functions_list: Accumulant = f( Accumulant )
    return Accumulant




def rgb_from_severity( severity ):
    """
    Convert the severity to RGB value
    (Legacy GUI function - returns default gray for RL-Agent non-GUI execution)
    """
    # Default gray color - not used in RL-Agent autonomous mode
    return (128, 128, 128)




def get_updated_severity( no_of_cities, resource_allocated, initial_severity ) -> [float]:
    """
    Update severity for existing cities given allocated resources as time progresses in the map.
    """

    UpdatedSeverity_list = []

    for c in range( no_of_cities ):

        InitialSeverityInCity    = initial_severity  [ c ]
        ResourcesAllocatedToCity = resource_allocated[ c ]
        NewSeverityInCity        = SEVERITY_MULTIPLIER * InitialSeverityInCity - RESPONSE_MULTIPLIER * ResourcesAllocatedToCity
        NewSeverityInCity        = max( NewSeverityInCity, 0 )

        UpdatedSeverity_list.append( NewSeverityInCity )


    return UpdatedSeverity_list




def sampler( samples, sum_to, range_list, rn = 100 ):
    """
    Obtain a number of random samples corresponding to some unknown criteria
    """

    # XXX My understanding here is that:
    #
    # - 'samples' here refers to the number of sequences in a block (typically initialised from 'NUM_SEQUENCES')
    #
    # - 'sum_to' is always set to 45, which I believe reflects the total number of trials that should exist in a block
    #   (i.e. over all sequences defined in that block). I have captured this number in the TOTAL_NUM_TRIALS_IN_BLOCK
    #   constant in the preamble of this module.
    #
    # - The intended use for the 'range_list' argument here is to contain the min and max number of trials that can be
    #   contained in a sequence (i.e. map)
    #
    # - 'rn' is an arbitrary number used as a seed. In practice it is passed the block number for which this function is
    #   called.
    #
    # - The sampler below works in two steps.
    #   1. In the first step, it says "obtain a random number of trials using a custom method, which involves getting
    #      the existing random slots containing numbers from 0 to num_of_sequences, and then come up with a new random
    #      number for each slot such this is the proportion of that random item in the slot over the sum of the whole
    #      array, and then multiplying by 45 (i.e. this is a method for obtaining a random number between 0 and 45), where
    #      45 represents the TOTAL_NUM_TRIALS_IN_BLOCK. If the number obtained is not between min_trials and max_trials,
    #      then discard this number and instead obtain a random number in that range normally using standard python
    #      facilities. It is not clear to me what advantage the custom method confers over standard python.
    #   2. In the second, while ensuring that entries are capped at min / max number of trials respectively, it either
    #      adds or subtracts from all number of trials randomly obtained in step 1, until a total of 45 trials is
    #      reached for the block

    assert range_list[ 0 ] < range_list[ 1 ], "Range should be a list, the first element of which is smaller than the second"

    numpy.random.seed( rn )

    arr = numpy.random.rand( samples )   # Arr represents a 'block', each entry represents a sequence, and the value of
                                         # each entry denotes the number of trials allocated randomly to that sequence
                                         # (subject to change below)

    sum_arr = sum( arr )   # The total number of trials in the block (we will later need to ensure this sums up to
                           # `sum_to`, i.e. 45)


  # Return a array, where values are first 'normalised' between 0 and `sum_to` (i.e. 45), and then 'validated' by only
  # keeping normalised values occurring between min_trials and max_trials, replacing invalid entries with a random
  # integer in that range.
    new_arr = numpy.array([
                          # (ternary operator syntax)
                                   int( item / sum_arr * sum_to )
                            if     (range_list[ 0 ] < int( item / sum_arr * sum_to ) < range_list[ 1 ])
                            else   numpy.random.choice( range( range_list[ 0 ], range_list[ 1 ] + 1 ) )

                          # within a list comprehension
                            for item in arr
                          ])

    difference = sum( new_arr ) - sum_to

  # Ensure that it is not possible for the while loop below to become infinite. This would occur in the following two
  # scenarios:
  #  1. The number of sequences in the block is so low,  that even if all sequences had the maximum number of trials, their sum would still always be below 45.
  #  2. The number of sequences in the block is so high, that even if all sequences had the minimum number of trials, their sum would still always be above 45.
  # E.g., for mintrials = 3 and maxtrials = 10, scenario 1 would occur for blocks having 4 sequences or fewer, and scenario 2 would occur for blocks having 16 sequences or higher.
  # Therefore the default selection of 8 sequences per block does not have this problem, but this may happen if this number is changed for testing purposes, so it is good to raise an exception here if this is the case.
  # (also see ticket:010)

    if len( samples ) * range_list[ 1 ] < sum_to   or   len( samples ) * range_list[ 0 ] > sum_to:
        raise ValueError( 'The specified number of sequences is such that the desired TOTAL_NUM_TRIALS_IN_BLOCK value can never be reached' )

    while difference != 0:

      # Sample indices (with replacement) as many times as needed to cover the difference, and increment or decrement at
      # those indices accordingly, to try to bring the difference up or down to 0 (i.e. such that the whole array sums
      # up to `sum_to` (i.e. 45)
        if difference < 0:
            for idx in numpy.random.choice( range( len( new_arr ) ), abs( difference ) ):
                if new_arr[ idx ] != range_list[ 1 ]:   new_arr[ idx ] += 1

        if difference > 0:
            for idx in numpy.random.choice( range( len( new_arr ) ), abs( difference ) ):
                if new_arr[ idx ] != 0 and new_arr[ idx ] != range_list[ 0 ]:   new_arr[ idx ] -= 1

        difference = sum( new_arr ) - sum_to


    return new_arr




def random_severity_generator( number_of_runs, lower_limit, upper_limit ):
    """
    Generate a random 'initial severity' value for each 'run' (i.e. city?)
    """

    x      = numpy.arange( lower_limit, upper_limit )
    xU, xL = x + 0.5, x - 0.5

    prob   = ss.norm.cdf( xU, scale = 100 ) - ss.norm.cdf( xL, scale = 100 )
    prob   = prob / prob.sum()  # normalize the probabilities so their sum is 1

    numpy.random.seed( 3 )

    nums = numpy.random.choice( x, size = number_of_runs, p = prob )


    return nums




def generate_feedback( SequenceIndices_1d_array, Performances, AllMessages, AggregatedAllocations, InitialSeveritiesInSequence ):
    """
    Create a plot object providing graphical feedback about the previous block.
    (Legacy GUI function - returns None for RL-Agent non-GUI execution)
    """
    # GUI feedback not available in RL-Agent autonomous mode
    return None




def next_seq_length(index, seq_per_block):
    """
    Based on current global seq index (0-359), retrieves the next 'seq_per_block' sequence lengths
    """
    SequenceLengthsCsv = os.path.join( INPUTS_PATH, SEQ_LENGTHS_FILE )
    s = numpy.loadtxt( SequenceLengthsCsv, delimiter=',' )
    sequence = s[ index : index + seq_per_block ]
    return sequence




def get_confidence_weighted_mean( all_messages, first_severity, AbsoluteSequenceIndex, AbsoluteTrialCount ):

    # First let's get the aggregated allocations
    NumTrials = numpy.shape( all_messages )[1]
    AggregatedAllocations = []

    for t in range( NumTrials ):

      # Get only valid responses and confidences for this trial
        TrialResponses   = numpy.array( all_messages )[ :, t, 0 ]
        TrialConfidences = numpy.array( all_messages )[ :, t, 1 ]

        OriginalTrialResponses = TrialResponses.copy()

        TrialResponses   = TrialResponses   [ TrialConfidences != -1 ]
        TrialConfidences = TrialConfidences [ TrialConfidences != -1 ]

      # TrialConfidences cannot be negative (-1 are already excluded)
      # So if the sum is zero, this means that all the values are zero
      # so they cannot be used as weight in numpy.average !
      # Let's all weigth one, and count in the same way (Ticket:085)
        if (numpy.sum( TrialConfidences ) == 0):
            TrialConfidences[:] = 1.0

      # In the unlikely case of no valid confidences, set the allocations to the plain mean of all participants
        if numpy.size( TrialConfidences ) == 0:
            ConfidenceWeightedMean = numpy.mean( OriginalTrialResponses )
        else:
            ConfidenceWeightedMean = numpy.average( TrialResponses, weights = TrialConfidences )

        AggregatedAllocations.append( ConfidenceWeightedMean )

    AggregatedAllocations = numpy.array( AggregatedAllocations )
    AggregatedAllocations = numpy.round( AggregatedAllocations )

  # Second, let's get the theoretical severity for that aggregate
    SeverityFromAggregate = get_array_of_sequence_severities_from_allocations( AggregatedAllocations, first_severity[ AbsoluteTrialCount - NumTrials : AbsoluteTrialCount ].copy() )


    return AggregatedAllocations, SeverityFromAggregate




def get_confidence_weighted_median( all_messages, first_severity,  AbsoluteSequenceIndex, AbsoluteTrialCount ):

  # First let's get the aggregated allocations
    NumTrials = numpy.shape( all_messages )[1]
    AggregatedAllocations = []

    for t in range( NumTrials ):

      # Get only valid responses and confidences for this trial
        TrialResponses   = numpy.array( all_messages )[ :, t, 0 ]
        TrialConfidences = numpy.array( all_messages )[ :, t, 1 ]

        OriginalTrialResponses = TrialResponses.copy()

        TrialResponses   = TrialResponses   [ TrialConfidences != -1 ]
        TrialConfidences = TrialConfidences [ TrialConfidences != -1 ]

      # In the unlikely case of no valid confidences, set the allocations to the plain median of all participants
        if numpy.size( TrialConfidences ) == 0:
            ConfidenceWeightedMedian = numpy.median( OriginalTrialResponses )
        else:

          # If only one valid response, duplicate for weightedmedian to work
            if numpy.size( TrialResponses ) == 1:
                TrialResponses   = numpy.repeat( TrialResponses  , 2 )
                TrialConfidences = numpy.repeat( TrialConfidences, 2 )

            ConfidenceWeightedMedian = WeightedStats(
                data    = TrialResponses,
                weights = TrialConfidences
            ).quantile(
                probs = [0.5],
                return_pandas = False
            )[0]

        AggregatedAllocations.append( ConfidenceWeightedMedian )

    AggregatedAllocations = numpy.array( AggregatedAllocations )
    AggregatedAllocations = numpy.round( AggregatedAllocations )

  # Second, let's get the theoretical severity for that aggregate
    SeverityFromAggregate = get_array_of_sequence_severities_from_allocations( AggregatedAllocations, first_severity[ AbsoluteTrialCount - NumTrials : AbsoluteTrialCount ].copy() )


    return AggregatedAllocations, SeverityFromAggregate




def get_actual_allocation_given_allocation_type( AggregatedAllocations, MyMessage, AllMessages ):

    global AllocationType

    MyConfidence        = MyMessage[ -1, 1 ] if MyMessage[ -1, 1 ] != -1 else 0
    SumOfAllConfidences = sum( Msg[ -1, 1 ] if Msg[ -1, 1 ] != -1 else 0 for Msg in AllMessages)
    ConfidenceRatio     = (MyConfidence / SumOfAllConfidences) if SumOfAllConfidences > 0 else 0

    allocated_resources_given_shared_allocation_type       = s = int( AggregatedAllocations[ -1 ] )
    allocated_resources_given_individual_allocation_type       = int( MyMessage[ -1, 0 ] )
    allocated_resources_given_penalised_allocation_type        = s
    allocated_resources_given_proportional_allocation_type     = s

    if   AllocationType == 'shared'      :   AllocatedResources = allocated_resources_given_shared_allocation_type
    elif AllocationType == 'individual'  :   AllocatedResources = allocated_resources_given_individual_allocation_type
    elif AllocationType == 'penalised'   :   AllocatedResources = allocated_resources_given_penalised_allocation_type
    elif AllocationType == 'proportional':   AllocatedResources = allocated_resources_given_proportional_allocation_type
    else: raise ValueError( f"Invalid value detected for variable AllocationType: '{AllocationType}'" )


    return AllocatedResources




def get_resources_left_given_allocation_type( CurrentResourcesLeft, AggregatedAllocations, MyMessage, AllMessages ):

    global AllocationType

    MyConfidence        = MyMessage[ -1, 1 ] if MyMessage[ -1, 1 ] != -1 else 0
    SumOfAllConfidences = sum( Msg[ -1, 1 ] if Msg[ -1, 1 ] != -1 else 0 for Msg in AllMessages)
    ConfidenceRatio     = (MyConfidence / SumOfAllConfidences) if SumOfAllConfidences > 0 else 0

    resources_left_given_shared_allocation_type       = s = int( CurrentResourcesLeft - AggregatedAllocations[-1] )
    resources_left_given_individual_allocation_type   = i = int( CurrentResourcesLeft - MyMessage[ -1, 0 ]        )
    resources_left_given_penalised_allocation_type        = min( s, i )
    resources_left_given_proportional_allocation_type     = round( CurrentResourcesLeft - AggregatedAllocations[ -1 ] * ConfidenceRatio )


    if   AllocationType == 'shared'      :   ResourcesLeft = resources_left_given_shared_allocation_type
    elif AllocationType == 'individual'  :   ResourcesLeft = resources_left_given_individual_allocation_type
    elif AllocationType == 'penalised'   :   ResourcesLeft = resources_left_given_penalised_allocation_type
    elif AllocationType == 'proportional':   ResourcesLeft = resources_left_given_proportional_allocation_type
    else: raise ValueError( f"Invalid value detected for variable AllocationType: '{AllocationType}'" )


    return ResourcesLeft




def toggle_experiment_mode( Mode = 'Solo' ):
    """
    Toggle experiment mode between 'Solo' (individual) and 'Joint' (shared allocation).
    Note: In RL-Agent mode, allocation is always 'individual' (Solo mode).
    """
    global AllocationType

    if Mode == 'Solo':
        AllocationType = 'individual'
    elif Mode == 'Joint':
        AllocationType = 'shared'
    else:
        raise ValueError( f"Invalid experiment mode given: {Mode}" )


def print_experiment_results_summary( MyPerformances, AllPerformances, LogUtils ):
    """
    Print a summary/balance of experiment results including statistics.
    """
    
    LogUtils.tee()
    LogUtils.tee( "=" * 80 )
    LogUtils.tee( "EXPERIMENT RESULTS SUMMARY" )
    LogUtils.tee( "=" * 80 )
    
    if len(MyPerformances) > 0:
        my_perf_array = numpy.array(MyPerformances)
        LogUtils.tee()
        LogUtils.tee( f"Agent Performance Statistics:" )
        LogUtils.tee( f"  - Mean Performance:        {numpy.mean(my_perf_array):.4f}" )
        LogUtils.tee( f"  - Std Deviation:           {numpy.std(my_perf_array):.4f}" )
        LogUtils.tee( f"  - Minimum Performance:     {numpy.min(my_perf_array):.4f}" )
        LogUtils.tee( f"  - Maximum Performance:     {numpy.max(my_perf_array):.4f}" )
        LogUtils.tee( f"  - Median Performance:      {numpy.median(my_perf_array):.4f}" )
        LogUtils.tee( f"  - Number of Sequences:     {len(MyPerformances)}" )
    
    if len(AllPerformances) > 1 and len(AllPerformances[1]) > 0:
        agg_perf_array = numpy.array(AllPerformances[1])
        LogUtils.tee()
        LogUtils.tee( f"Aggregated Performance Statistics:" )
        LogUtils.tee( f"  - Mean Performance:        {numpy.mean(agg_perf_array):.4f}" )
        LogUtils.tee( f"  - Std Deviation:           {numpy.std(agg_perf_array):.4f}" )
        LogUtils.tee( f"  - Minimum Performance:     {numpy.min(agg_perf_array):.4f}" )
        LogUtils.tee( f"  - Maximum Performance:     {numpy.max(agg_perf_array):.4f}" )
    
    LogUtils.tee( "=" * 80 )
    LogUtils.tee()


def plot_experiment_results( MyPerformances, AllPerformances, OutputPath, SubjectId, LogUtils ):
    """
    Generate plots of experiment results and save them.
    """
    
    import matplotlib.pyplot as plt
    
    try:
        # Create figure with subplots
        fig, axes = plt.subplots(2, 2, figsize=(14, 10))
        fig.suptitle(f'Experiment Results - Subject {SubjectId}', fontsize=16, fontweight='bold')
        
        # Plot 1: Agent Performance over Sequences
        if len(MyPerformances) > 0:
            ax = axes[0, 0]
            ax.plot(MyPerformances, 'b-o', linewidth=2, markersize=4)
            ax.fill_between(range(len(MyPerformances)), MyPerformances, alpha=0.3)
            ax.set_xlabel('Sequence Number')
            ax.set_ylabel('Performance Score')
            ax.set_title('Agent Performance Across Sequences')
            ax.grid(True, alpha=0.3)
            ax.set_ylim([0, 1.05])
        
        # Plot 2: Performance Distribution
        if len(MyPerformances) > 0:
            ax = axes[0, 1]
            ax.hist(MyPerformances, bins=15, color='skyblue', edgecolor='black', alpha=0.7)
            ax.axvline(numpy.mean(MyPerformances), color='red', linestyle='--', linewidth=2, label=f'Mean: {numpy.mean(MyPerformances):.3f}')
            ax.axvline(numpy.median(MyPerformances), color='green', linestyle='--', linewidth=2, label=f'Median: {numpy.median(MyPerformances):.3f}')
            ax.set_xlabel('Performance Score')
            ax.set_ylabel('Frequency')
            ax.set_title('Performance Distribution')
            ax.legend()
            ax.grid(True, alpha=0.3, axis='y')
        
        # Plot 3: Cumulative Average Performance
        if len(MyPerformances) > 0:
            ax = axes[1, 0]
            cumulative_avg = numpy.cumsum(MyPerformances) / numpy.arange(1, len(MyPerformances) + 1)
            ax.plot(cumulative_avg, 'g-', linewidth=2)
            ax.fill_between(range(len(cumulative_avg)), cumulative_avg, alpha=0.3, color='green')
            ax.set_xlabel('Sequence Number')
            ax.set_ylabel('Cumulative Average Performance')
            ax.set_title('Learning Curve (Cumulative Average)')
            ax.grid(True, alpha=0.3)
            ax.set_ylim([0, 1.05])
        
        # Plot 4: Agent vs Aggregated Performance
        if len(MyPerformances) > 0 and len(AllPerformances) > 1 and len(AllPerformances[1]) > 0:
            ax = axes[1, 1]
            ax.plot(MyPerformances, 'b-o', linewidth=2, markersize=4, label='Agent Performance')
            ax.plot(AllPerformances[1], 'r-s', linewidth=2, markersize=4, label='Aggregated Performance')
            ax.set_xlabel('Sequence Number')
            ax.set_ylabel('Performance Score')
            ax.set_title('Agent vs Aggregated Performance')
            ax.legend()
            ax.grid(True, alpha=0.3)
            ax.set_ylim([0, 1.05])
        
        plt.tight_layout()
        
        # Save figure
        plot_filename = os.path.join(OutputPath, f'{OUTPUT_FILE_PREFIX}performance_plot_{SubjectId}.png')
        plt.savefig(plot_filename, dpi=150, bbox_inches='tight')
        LogUtils.tee(f"Performance plot saved to: {plot_filename}")
        
        # Also create a statistics plot
        fig2, ax = plt.subplots(figsize=(10, 6))
        
        if len(MyPerformances) > 0:
            my_perf_array = numpy.array(MyPerformances)
            stats_labels = ['Mean', 'Std Dev', 'Min', 'Max', 'Median']
            stats_values = [
                numpy.mean(my_perf_array),
                numpy.std(my_perf_array),
                numpy.min(my_perf_array),
                numpy.max(my_perf_array),
                numpy.median(my_perf_array)
            ]
            
            colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']
            bars = ax.bar(stats_labels, stats_values, color=colors, alpha=0.7, edgecolor='black', linewidth=1.5)
            
            # Add value labels on bars
            for bar, value in zip(bars, stats_values):
                height = bar.get_height()
                ax.text(bar.get_x() + bar.get_width()/2., height,
                       f'{value:.3f}',
                       ha='center', va='bottom', fontsize=11, fontweight='bold')
            
            ax.set_ylabel('Performance Score', fontsize=12)
            ax.set_title(f'Performance Statistics - Subject {SubjectId}', fontsize=14, fontweight='bold')
            ax.set_ylim([0, max(stats_values) * 1.15])
            ax.grid(True, alpha=0.3, axis='y')
        
        plt.tight_layout()
        stats_filename = os.path.join(OutputPath, f'{OUTPUT_FILE_PREFIX}performance_stats_{SubjectId}.png')
        plt.savefig(stats_filename, dpi=150, bbox_inches='tight')
        LogUtils.tee(f"Statistics plot saved to: {stats_filename}")
        
        plt.close('all')
        
    except Exception as e:
        LogUtils.tee(f"Warning: Could not generate plots: {str(e)}")
